"""全局常量和配置"""

# 摄像头配置
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30

# 手势识别配置
HAND_DETECTION_CONFIDENCE = 0.7
HAND_TRACKING_CONFIDENCE = 0.5
MAX_NUM_HANDS = 2

# 鼠标控制配置
MOUSE_SMOOTH_FACTOR = 0.2
MOUSE_MAX_VELOCITY = 100
CLICK_INTERVAL = 3  # 秒

# 界面配置
WINDOW_TITLE = "隔空控制鼠标"
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
VIDEO_LABEL_MIN_WIDTH = 640
VIDEO_LABEL_MIN_HEIGHT = 480

# 更新频率配置
TIMER_INTERVAL_MS = 30  # 约33 FPS

# 手势识别灵敏度配置
SMALL_MOVEMENT_THRESHOLD = 5
MEDIUM_MOVEMENT_THRESHOLD = 15
SMALL_MOVEMENT_SENSITIVITY = 15.0
MEDIUM_MOVEMENT_SENSITIVITY = 20.0
BASE_LARGE_MOVEMENT_SENSITIVITY = 25.0